name = "PowerModelsACDCsecurityconstrained"
uuid = "bf5a9aac-8200-4ea2-86f6-b4ae0f6a6384"
authors = ["GHULAM MOHY UD DIN <g.mohyuddinuett@gmail.com>"]
version = "0.1.0"

[deps]
CalculusWithJulia = "a2e0e22d-7d4c-5312-9169-8b992201a882"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsACDC = "ff45984e-d068-5f4c-9e32-c4133509d236"
PowerModelsSecurityConstrained = "53333297-f92c-5019-980b-942fc744b407"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Cbc = "1.2.0"
HiGHS = "1.17.0"
Juniper = "0.9.3"
PowerModels = "0.19.10"
